block commit on main

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,3 +4,8 @@
 cd `dirname -- $0` # cd /path/to/coursemate/_/husky.sh
 cd ../..
 # now the wd is at /coursemate
+
+if [ `git branch --show-current` == "main" ]; then
+  echo "Cannot make commit on main! aborting..."
+  exit 1
+fi
